// Modules
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from '@mantine/notifications';
import { ClerkProvider } from "@clerk/nextjs";
import StoreProvider from "./redux/StoreProvider";

import "@mantine/core/styles.css";
import "@mantine/charts/styles.css";
import '@mantine/notifications/styles.css';
// Componets
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#4f976b",
        },
      }}
    >
      <StoreProvider>
        <html lang="en">
          <head>
            <ColorSchemeScript />
            <title>Team GPT PRO !!!</title>
          </head>
          <body className={inter.className}>
            <MantineProvider defaultColorScheme="dark">
              <Notifications />
              {children}
            </MantineProvider>
          </body>
        </html>
      </StoreProvider>
    </ClerkProvider>
  );
}
